Algoritmo "Media"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/6/2022
Var
// Seção de Declarações das variáveis 
   n1, n2, s: inteiro
   m: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite N1: ")
   leia(n1)
   escreva("Digite N2: ")
   leia(n2)
   s <- n1 + n2
   m <- s / 2
   escreval("Soma:",s)
   escreva("Média:",m)

Fimalgoritmo