Algoritmo "MeuNome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/6/2022
Var
// Seção de Declarações das variáveis 
   nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
// nome <- "Weskley"
// escreva("Ola, ", nome)
   escreva("Digite seu nome: ")
   leia(nome)
   escreva("Ola, ", nome)

Fimalgoritmo