Algoritmo "OlaMundo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/6/2022
Var
// Seção de Declarações das variáveis 
   msg: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   msg <- "Ola Mundo"
   escreval("Mensagem: ", msg)
   escreva("Estudando algoritmo")

Fimalgoritmo